name: "default"
config-version: 2
version: "2.0"

require-dbt-version: ">=1.0.0"

profile: "postgres"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

seeds:
  default:
    lnd:
      schema: lnd


models:
  default:
    rfd:
      enabled: true
      materialized: table
      schema: rfd